# Preview all emails at http://localhost:3000/rails/mailers/transactional_mailer
class TransactionalMailerPreview < ActionMailer::Preview
  def alacarte_email
    pdt_hash = { "mc_gross" => "40.90",
                 "protection_eligibility" => "Eligible",
                 "address_status" => "confirmed",
                 "item_number1" => "bv-clearing-kit",
                 "payer_id" => "5BLERWEPAC3WN",
                 "tax" => "0.00",
                 "address_street" => "P.O. box 154",
                 "payment_date" => "11:46:08 Jan 18, 2018 PST",
                 "payment_status" => "Completed",
                 "charset" => "windows-1252",
                 "address_zip" => "96128",
                 "mc_shipping" => "5.95",
                 "mc_handling" => "0.00",
                 "first_name" => "cody",
                 "mc_fee" => "1.49",
                 "address_country_code" => "US",
                 "address_name" => "cody chandler",
                 "payer_status" => "unverified",
                 "business" => "neueve.suppositories@gmail.com",
                 "address_country" => "United States",
                 "num_cart_items" => "1",
                 "mc_handling1" => "0.00",
                 "address_city" => "Standish",
                 "payer_email" => "sweetcrazyunstable@yahoo.com",
                 "mc_shipping1" => "0.00",
                 "tax1" => "0.00",
                 "btn_id1" => "95609135",
                 "txn_id" => "2DV9337609417074S",
                 "payment_type" => "instant",
                 "last_name" => "chandler",
                 "address_state" => "CA",
                 "item_name1" => "NeuEve BV Clearing Kit",
                 "receiver_email" => "neueve.suppositories@gmail.com",
                 "payment_fee" => "1.49",
                 "shipping_discount" => "0.00",
                 "quantity1" => "1",
                 "insurance_amount" => "0.00",
                 "receiver_id" => "TERMWE8J86S96",
                 "txn_type" => "cart",
                 "discount" => "0.00",
                 "mc_gross_1" => "34.95",
                 "mc_currency" => "USD",
                 "residence_country" => "US",
                 "receipt_id" => "4085-7657-4119-4839",
                 "shipping_method" => "Standard Domestic",
                 "payment_gross" => "40.90" }
    TransactionalMailer.alacarte_email(pdt_hash)
  end

  def three_item_alacarte_email
    pdt_hash = { "first_name" => "Jo",
                 "discount" => "0.00",
                 "mc_shipping" => "0.00",
                 "mc_currency" => "USD",
                 "payer_status" => "unverified",
                 "shipping_discount" => "0.00",
                 "payment_fee" => "2.96",
                 "address_status" => "confirmed",
                 "payment_gross" => "91.85",
                 "address_zip" => "26104",
                 "txn_type" => "cart",
                 "num_cart_items" => "3",
                 "address_country_code" => "US",
                 "mc_handling" => "0.00",
                 "payer_id" => "QHMMVBCH7P4EW",
                 "charset" => "windows-1252",
                 "tax1" => "0.00",
                 "receiver_id" => "TERMWE8J86S96",
                 "tax2" => "0.00",
                 "tax3" => "0.00",
                 "mc_handling1" => "0.00",
                 "mc_handling2" => "0.00",
                 "mc_handling3" => "0.00",
                 "btn_id1" => "80140067",
                 "item_name1" => "NeuEve Silk Formula (1 month supply)",
                 "tax" => "0.00",
                 "btn_id2" => "80140090",
                 "item_name2" => "NeuEve Cream (2-3 month supply)",
                 "btn_id3" => "89149863",
                 "item_name3" => "Suppository Applicator,
 Reusable",
                 "payment_type" => "instant",
                 "mc_shipping1" => "0.00",
                 "address_street" => "273 Captain Ames Drive",
                 "mc_shipping2" => "0.00",
                 "mc_shipping3" => "0.00",
                 "txn_id" => "89G72487KD342213Y",
                 "mc_gross_1" => "51.95",
                 "quantity1" => "1",
                 "mc_gross_2" => "34.95",
                 "quantity2" => "1",
                 "item_number1" => "silk",
                 "protection_eligibility" => "Eligible",
                 "mc_gross_3" => "4.95",
                 "quantity3" => "1",
                 "item_number2" => "cream",
                 "item_number3" => "applicator",
                 "business" => "neueve.suppositories@gmail.com",
                 "residence_country" => "US",
                 "last_name" => "Boggs",
                 "address_state" => "WV",
                 "payer_email" => "JoAnn.Boggs@gmail.com",
                 "address_city" => "Parkersburg",
                 "payment_status" => "Completed",
                 "payment_date" => "17:02:07 Jan 18,
 2018 PST",
                 "receiver_email" => "neueve.suppositories@gmail.com",
                 "mc_fee" => "2.96",
                 "shipping_method" => "Standard Domestic",
                 "address_country" => "United States",
                 "receipt_id" => "3360-1597-1608-6170",
                 "mc_gross" => "91.85",
                 "insurance_amount" => "0.00",
                 "address_name" => "Jo Boggs" }
    TransactionalMailer.alacarte_email(pdt_hash)
  end

  def subscription_email
    pdt_data = {"mc_gross"=>"46.75",
                "protection_eligibility"=>"Eligible",
                "address_status"=>"confirmed",
                "payer_id"=>"NNVYMZRMAZEJL",
                "address_street"=>"12601 County Road 2170",
                "payment_date"=>"11:51:59 Jan 15,
2018 PST",
                "payment_status"=>"Completed",
                "charset"=>"windows-1252",
                "address_zip"=>"65559",
                "first_name"=>"becki",
                "option_selection1"=>"NeuEve Silver (USA)",
                "mc_fee"=>"1.66",
                "address_country_code"=>"US",
                "address_name"=>"Becki Weitzsacker",
                "subscr_id"=>"I-4FJK05W6F7DV",
                "payer_status"=>"verified",
                "business"=>"neueve.suppositories@gmail.com",
                "address_country"=>"United States",
                "address_city"=>"Saint James",
                "payer_email"=>"chewymama73@gmail.com",
                "option_name1"=>"Formula",
                "txn_id"=>"6J530244LX7440914",
                "payment_type"=>"instant",
                "btn_id"=>"65256911",
                "last_name"=>"pyatt",
                "address_state"=>"MO",
                "receiver_email"=>"neueve.suppositories@gmail.com",
                "payment_fee"=>"1.66",
                "receiver_id"=>"TERMWE8J86S96",
                "txn_type"=>"subscr_payment",
                "item_name"=>"NeuEve Subscription",
                "mc_currency"=>"USD",
                "item_number"=>"silver",
                "residence_country"=>"US",
                "transaction_subject"=>"NeuEve Subscription",
                "payment_gross"=>"46.75"}
    TransactionalMailer.subscription_email(pdt_data)
  end
end
